openapi: 3.0.0
info:
  title: books
  version: 1.0.0
servers:
- url: http://localhost:9000
paths:
  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: A list of books
    post:
      summary: Create a new book
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                completed:
                  type: boolean
              example:
                title: Linear books
                completed: false
      responses:
        '201':
          description: Book created
  /books/{id}:
    get:
      summary: Get a book by ID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: A book
        '404':
          description: Book not found
    put:
      summary: Update a book by ID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
              example:
                completed: true
      responses:
        '200':
          description: Book updated
        '404':
          description: Book not found
    delete:
      summary: Delete a book by ID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Book deleted
        '404':
          description: Book not found