openapi: 3.0.0
info:
  title: books
  version: 1.0.0
servers:
  - url: localhost://
paths:
  /000/books:
    post:
      tags:
        - default
      summary: give new book
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Linear books
                completed: 'False'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /000/books/2:
    put:
      tags:
        - default
      summary: update book info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                completed: 'True'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /000/books/3:
    delete:
      tags:
        - default
      summary: Delete book by id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /000/books/1:
    get:
      tags:
        - default
      summary: get a book by id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}